title: Azrael69
description: "Enterprise Data Management Portfolio"
theme: jekyll-theme-minimal
logo: "Midterm task 1/Image/Screenshot_2025-03-15-20-14-07-316_com.lenovo.anyshare.gps-edit.jpg"
show_downloads: true
