theme: "midnight-tether"

profile:
  image: "Midterm task 1/Image/20250312_004417_0000.png"
  shape: "circle"

colors:
  background: "#0d0d0d"
  text: "#ffffff"
  accent: "#1db954"
  border: "#1a1a1a"

fonts:
  header: "Poppins, sans-serif"
  body: "Roboto, sans-serif"

animations:
  - type: "fade-in"
    duration: "1s"
  - type: "hover-zoom"

show_downloads: true

footer: "🚀 Keep innovating, keep learning!"
