title: "Azrael's Portfolio"
theme: "jekyll-theme-midnight"
show_downloads: true
description: "Welcome to my portfolio, showcasing my projects and journey in Information Systems."
author: "Azrael"

profile:
  image: "https://raw.githubusercontent.com/Azrael2001/Azrael69/main/Midterm%20task%201/Image/Logo.jpg"
  shape: "circle"
