title: Azrael69
avatar: "https://github.com/Azrael2001/Azrael69/blob/b07a395dd1bb8168c94006edb011eafcf1f6b38c/Midterm%20task%201/Image/Logo.jpg"
description: Student of IT
show downloads: true
theme: jekyll-theme-minimal
