title: "Azreal Portfolio"
logo: "https://raw.githubusercontent.com/Azrael2001/Azrael69/main/Midterm%20task%201/Image/Logo.jpg"
description: "MAMA NI AZRAEL"
show_downloads: false
remote_theme: "pages-themes/midnight@v0.2.0"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown
theme: jekyll-theme-midnight
sass:
  style: compressed

include:
  - _includes
  - _layouts
